# Generated by Django 5.2.15 on 2026-06-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=120)),
                ('transport', models.CharField(max_length=60)),
                ('depart_at', models.DateTimeField()),
                ('arrive_at', models.DateTimeField()),
                ('pax', models.PositiveSmallIntegerField()),
                ('kids', models.JSONField(default=list)),
                ('hotel_name', models.CharField(max_length=120)),
                ('hotel_address', models.CharField(max_length=200)),
                ('is_apartments', models.BooleanField(default=False)),
                ('weather', models.JSONField(default=dict)),
                ('emergency', models.JSONField(default=list)),
                ('phase', models.PositiveSmallIntegerField(default=0)),
                ('step_index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('ai', 'ai'), ('user', 'user'), ('time', 'time'), ('concern', 'concern'), ('sys', 'sys'), ('results', 'results')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('plan_amount', models.PositiveIntegerField()),
                ('fact_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('prepaid', 'prepaid'), ('variable', 'variable')], max_length=10)),
                ('order', models.PositiveSmallIntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('icon', models.CharField(max_length=8)),
                ('service', models.CharField(max_length=80)),
                ('phase', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('locked', 'locked'), ('wait', 'wait'), ('done', 'done')], default='locked', max_length=8)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=2)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'key'), name='uniq_trip_planitem')],
            },
        ),
    ]
