# Generated by Django 5.2.15 on 2026-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='address_pending',
            field=models.BooleanField(default=False),
        ),
    ]
